services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - "127.0.1.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
  # --- Service Backend (Node/Express) ---
  backend:
    build: ./back
    container_name: projet-back
    ports:
      - "3000:3000" # Expose l'API sur le port 3000 du PC
    environment:
      DB_HOST: mariadb 
      DB_USER: root
      DB_PASSWORD: toor
      DB_NAME: db
      DB_PORT: 3306
    depends_on:
      mariadb:
        condition: service_healthy

  # --- Service Frontend (Angular/Nginx) ---
  frontend:
    build: ./front
    container_name: projet-front
    ports:
      - "4200:80" # On map le port 4200 de ton PC vers le port 80 du conteneur Nginx
    depends_on:
      - backend
volumes:
  mariadb_data: