version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - "127.0.1.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  app_backend:
    build:
      context: ./back
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=toor
      - DB_NAME=db
      - DB_PORT=3306
    entrypoint: ["/bin/sh", "-c", "sleep 10 && node main.js"]
    ports:
      - "3000:3000"
  # app_frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - app_backend
  #   ports:
  #     - "4200:4200"
volumes:
  mariadb_data: